language: php

sudo: false

php:
  - 5.5.9
  - 5.6
  - 7.0
  - 7.1

install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

before_script:
  - bash vendor/frozzare/wp-test-suite/bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 $WP_VERSION
  - bash tests/bin/install-wp-cli.sh

script:
  - vendor/bin/phpunit --coverage-clover clover.xml
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then vendor/bin/behat; fi

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - bash <(curl -s https://codecov.io/bash)

env:
  matrix:
    - WP_VERSION=4.0 WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=0
  global:
    - WP_CLI_BIN_DIR=/tmp/wp-cli-phar
    - WP_CLI_CONFIG_PATH=/tmp/wp-cli-phar/config.yml

cache:
  directories:
  - $HOME/.composer/cache

branches:
  only:
    - master
    - 2.x
    - 3.x
